import 'package:learn2save_lms_flutter_app/models/user_model.dart';
import 'package:learn2save_lms_flutter_app/models/assessment_model.dart';
import 'package:learn2save_lms_flutter_app/models/course_model.dart';

class DummyData {
  // Dummy Admin User
  static final User adminUser = User(
    id: 'admin',
    name: 'Admin User',
    email: 'admin@savemore.com',
    avatar: 'https://picsum.photos/seed/admin/200/200',
    bio: 'System Administrator',
    enrolledCourses: [],
    completedCourses: [],
    achievements: ['System Administrator'],
    joinDate: DateTime(2022, 1, 1),
    totalLearningHours: 0,
    role: 'admin',
  );

  // Dummy Users
  static final User currentUser = User(
    id: '1',
    name: 'Abdul Wahab',
    email: 'savemore@gmail.com',
    avatar: 'https://picsum.photos/seed/user1/200/200',
    bio: 'Passionate learner and tech enthusiast',
    enrolledCourses: ['1', '2', '3'],
    completedCourses: ['4'],
    achievements: [
      'Fast Learner',
      'Quiz Master',
      'Consistent Student',
    ],
    joinDate: DateTime(2023, 1, 15),
    totalLearningHours: 156,
    role: 'student',
  );

  // Additional dummy users for admin management
  static final List<User> allUsers = [
    currentUser,
    User(
      id: '2',
      name: 'Jane Smith',
      email: 'jane.smith@example.com',
      avatar: 'https://picsum.photos/seed/user2/200/200',
      bio: 'Design enthusiast',
      enrolledCourses: ['4', '5'],
      completedCourses: [],
      achievements: ['New Member'],
      joinDate: DateTime(2023, 2, 20),
      totalLearningHours: 45,
      role: 'student',
    ),
    User(
      id: '3',
      name: 'Robert Johnson',
      email: 'robert.johnson@example.com',
      avatar: 'https://picsum.photos/seed/user3/200/200',
      bio: 'Data science enthusiast',
      enrolledCourses: ['3'],
      completedCourses: ['1', '2'],
      achievements: ['Fast Learner', 'Data Analyst'],
      joinDate: DateTime(2023, 3, 10),
      totalLearningHours: 230,
      role: 'student',
    ),
    User(
      id: '4',
      name: 'Emily Davis',
      email: 'emily.davis@example.com',
      avatar: 'https://picsum.photos/seed/user4/200/200',
      bio: 'Marketing professional',
      enrolledCourses: ['5'],
      completedCourses: [],
      achievements: ['New Member'],
      joinDate: DateTime(2023, 4, 5),
      totalLearningHours: 20,
      role: 'student',
    ),
  ];

  // Dummy Courses
  static final List<Course> courses = [
    Course(
      id: '1',
      title: 'Flutter Development Masterclass',
      description: 'Learn Flutter from scratch and build beautiful mobile applications',
      instructor: 'Sarah Johnson',
      instructorAvatar: 'https://picsum.photos/seed/instructor1/100/100',
      thumbnail: 'https://picsum.photos/seed/course1/400/250',
      duration: '12 hours',
      lessons: 48,
      students: 15234,
      rating: 4.8,
      price: 89.99,
      category: 'Mobile Development',
      level: 'Intermediate',
      language: 'English',
      lastUpdated: DateTime(2024, 1, 10),
      curriculum: [
        'Introduction to Flutter',
        'Dart Programming Basics',
        'Widgets and Layouts',
        'State Management',
        'Navigation and Routing',
        'Networking and APIs',
        'Firebase Integration',
        'Publishing Apps',
      ],
      enrolled: true,
      progress: 0.65,
    ),
    Course(
      id: '2',
      title: 'Web Development with React',
      description: 'Master React and build modern web applications',
      instructor: 'Mike Chen',
      instructorAvatar: 'https://picsum.photos/seed/instructor2/100/100',
      thumbnail: 'https://picsum.photos/seed/course2/400/250',
      duration: '15 hours',
      lessons: 62,
      students: 18923,
      rating: 4.7,
      price: 99.99,
      category: 'Web Development',
      level: 'Beginner',
      language: 'English',
      lastUpdated: DateTime(2024, 1, 5),
      curriculum: [
        'React Fundamentals',
        'Components and Props',
        'State and Lifecycle',
        'Hooks Deep Dive',
        'Context API',
        'React Router',
        'Redux Integration',
        'Testing React Apps',
      ],
      enrolled: true,
      progress: 0.40,
    ),
    Course(
      id: '3',
      title: 'Python for Data Science',
      description: 'Learn Python and explore the world of data science',
      instructor: 'Dr. Emily Brown',
      instructorAvatar: 'https://picsum.photos/seed/instructor3/100/100',
      thumbnail: 'https://picsum.photos/seed/course3/400/250',
      duration: '20 hours',
      lessons: 75,
      students: 23456,
      rating: 4.9,
      price: 129.99,
      category: 'Data Science',
      level: 'Intermediate',
      language: 'English',
      lastUpdated: DateTime(2024, 1, 8),
      curriculum: [
        'Python Basics',
        'NumPy and Pandas',
        'Data Visualization',
        'Statistical Analysis',
        'Machine Learning Intro',
        'Deep Learning Basics',
        'Real-world Projects',
      ],
      enrolled: true,
      progress: 0.25,
    ),
    Course(
      id: '4',
      title: 'UI/UX Design Fundamentals',
      description: 'Create stunning user interfaces and experiences',
      instructor: 'Alex Rivera',
      instructorAvatar: 'https://picsum.photos/seed/instructor4/100/100',
      thumbnail: 'https://picsum.photos/seed/course4/400/250',
      duration: '10 hours',
      lessons: 40,
      students: 12456,
      rating: 4.6,
      price: 79.99,
      category: 'Design',
      level: 'Beginner',
      language: 'English',
      lastUpdated: DateTime(2024, 1, 12),
      curriculum: [
        'Design Principles',
        'Color Theory',
        'Typography',
        'Layout Design',
        'Prototyping',
        'User Research',
        'Design Tools',
      ],
      enrolled: false,
      progress: 0.0,
    ),
    Course(
      id: '5',
      title: 'Digital Marketing Strategy',
      description: 'Master digital marketing and grow your business',
      instructor: 'Lisa Anderson',
      instructorAvatar: 'https://picsum.photos/seed/instructor5/100/100',
      thumbnail: 'https://picsum.photos/seed/course5/400/250',
      duration: '8 hours',
      lessons: 35,
      students: 9876,
      rating: 4.5,
      price: 69.99,
      category: 'Marketing',
      level: 'Beginner',
      language: 'English',
      lastUpdated: DateTime(2024, 1, 3),
      curriculum: [
        'Marketing Fundamentals',
        'SEO Basics',
        'Social Media Marketing',
        'Content Marketing',
        'Email Marketing',
        'Analytics and Metrics',
      ],
      enrolled: false,
      progress: 0.0,
    ),
    // Additional courses for admin management
    Course(
      id: '6',
      title: 'Advanced JavaScript',
      description: 'Master advanced JavaScript concepts and techniques',
      instructor: 'David Wilson',
      instructorAvatar: 'https://picsum.photos/seed/instructor6/100/100',
      thumbnail: 'https://picsum.photos/seed/course6/400/250',
      duration: '18 hours',
      lessons: 72,
      students: 8765,
      rating: 4.7,
      price: 109.99,
      category: 'Web Development',
      level: 'Advanced',
      language: 'English',
      lastUpdated: DateTime(2024, 1, 15),
      curriculum: [
        'Advanced Functions',
        'Closures and Scope',
        'Prototypes and Inheritance',
        'Async Programming',
        'ES6+ Features',
        'Design Patterns',
        'Performance Optimization',
        'Testing and Debugging',
      ],
      enrolled: false,
      progress: 0.0,
    ),
    Course(
      id: '7',
      title: 'Machine Learning with TensorFlow',
      description: 'Build and deploy machine learning models with TensorFlow',
      instructor: 'Dr. Michael Lee',
      instructorAvatar: 'https://picsum.photos/seed/instructor7/100/100',
      thumbnail: 'https://picsum.photos/seed/course7/400/250',
      duration: '25 hours',
      lessons: 90,
      students: 6543,
      rating: 4.8,
      price: 149.99,
      category: 'Data Science',
      level: 'Advanced',
      language: 'English',
      lastUpdated: DateTime(2024, 1, 20),
      curriculum: [
        'Introduction to TensorFlow',
        'Neural Networks Basics',
        'Convolutional Neural Networks',
        'Recurrent Neural Networks',
        'Transfer Learning',
        'Model Deployment',
        'TensorFlow Extended',
        'Real-world Projects',
      ],
      enrolled: false,
      progress: 0.0,
    ),
  ];

  // Dummy Quizzes
  static final List<Quiz> quizzes = [
    Quiz(
      id: '1',
      title: 'Flutter Basics Quiz',
      courseId: '1',
      duration: 30, // minutes
      questions: [
        Question(
          id: '1',
          text: 'What is Flutter?',
          options: [
            'A programming language',
            'A UI toolkit for building apps',
            'A database system',
            'An operating system',
          ],
          correctAnswer: 1,
        ),
        Question(
          id: '2',
          text: 'Which language is used in Flutter?',
          options: [
            'Java',
            'Swift',
            'Dart',
            'Kotlin',
          ],
          correctAnswer: 2,
        ),
        Question(
          id: '3',
          text: 'What is a Widget in Flutter?',
          options: [
            'A button component',
            'A building block of UI',
            'A database record',
            'A network request',
          ],
          correctAnswer: 1,
        ),
      ],
    ),
    Quiz(
      id: '2',
      title: 'React Components Quiz',
      courseId: '2',
      duration: 25,
      questions: [
        Question(
          id: '1',
          text: 'What is JSX?',
          options: [
            'A JavaScript framework',
            'A syntax extension for JavaScript',
            'A styling language',
            'A database query language',
          ],
          correctAnswer: 1,
        ),
        Question(
          id: '2',
          text: 'What hook is used for state management?',
          options: [
            'useEffect',
            'useState',
            'useContext',
            'useReducer',
          ],
          correctAnswer: 1,
        ),
      ],
    ),
    // Additional quizzes for admin management
    Quiz(
      id: '3',
      title: 'Python Fundamentals Quiz',
      courseId: '3',
      duration: 40,
      questions: [
        Question(
          id: '1',
          text: 'What is Python?',
          options: [
            'A compiled language',
            'An interpreted language',
            'A markup language',
            'A database system',
          ],
          correctAnswer: 1,
        ),
        Question(
          id: '2',
          text: 'Which of the following is used to define a function in Python?',
          options: [
            'function',
            'def',
            'func',
            'define',
          ],
          correctAnswer: 1,
        ),
        Question(
          id: '3',
          text: 'What is the correct file extension for Python files?',
          options: [
            '.py',
            '.python',
            '.pt',
            '.pyt',
          ],
          correctAnswer: 0,
        ),
      ],
    ),
    Quiz(
      id: '4',
      title: 'UI/UX Design Principles Quiz',
      courseId: '4',
      duration: 20,
      questions: [
        Question(
          id: '1',
          text: 'What does UI stand for?',
          options: [
            'User Interface',
            'User Interaction',
            'User Integration',
            'User Interest',
          ],
          correctAnswer: 0,
        ),
        Question(
          id: '2',
          text: 'What does UX stand for?',
          options: [
            'User Experience',
            'User Exchange',
            'User Extension',
            'User Exploration',
          ],
          correctAnswer: 0,
        ),
      ],
    ),
  ];

  // Dummy Notifications
  static final List<NotificationItem> notifications = [
    NotificationItem(
      id: '1',
      title: 'New Course Available',
      message: 'Check out our new course on Advanced Flutter',
      timestamp: DateTime.now().subtract(const Duration(hours: 2)),
      isRead: false,
      type: 'course',
    ),
    NotificationItem(
      id: '2',
      title: 'Quiz Reminder',
      message: 'You have a quiz due tomorrow',
      timestamp: DateTime.now().subtract(const Duration(hours: 5)),
      isRead: false,
      type: 'quiz',
    ),
    NotificationItem(
      id: '3',
      title: 'Achievement Unlocked',
      message: 'Congratulations! You completed 5 courses',
      timestamp: DateTime.now().subtract(const Duration(days: 1)),
      isRead: true,
      type: 'achievement',
    ),
    NotificationItem(
      id: '4',
      title: 'Course Update',
      message: 'New lessons added to Flutter Development',
      timestamp: DateTime.now().subtract(const Duration(days: 2)),
      isRead: true,
      type: 'update',
    ),
  ];

  // Categories
  static final List<String> categories = [
    'All',
    'Mobile Development',
    'Web Development',
    'Data Science',
    'Design',
    'Marketing',
    'Business',
    'Photography',
  ];

  // Analytics data for admin dashboard
  static final Map<String, dynamic> analyticsData = {
    'totalUsers': 1250,
    'activeUsers': 890,
    'totalCourses': courses.length,
    'totalEnrollments': 3456,
    'totalRevenue': 125670.50,
    'monthlyRevenue': [12000, 15000, 18000, 22000, 19000, 25000],
    'courseEnrollments': {
      'Flutter Development Masterclass': 15234,
      'Web Development with React': 18923,
      'Python for Data Science': 23456,
      'UI/UX Design Fundamentals': 12456,
      'Digital Marketing Strategy': 9876,
    },
    'userGrowth': [100, 150, 200, 280, 350, 450, 550, 680, 790, 890, 1050, 1250],
    'courseCompletions': {
      'completed': 2340,
      'inProgress': 1116,
    },
  };
}